version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

    networks:
      - SenaSoft

  participacionciudadana:
    image: participacion-ciudadana
    container_name: participacion-ciudadana
    ports:
      - '8080:8080'

    networks:
      - SenaSoft

    depends_on:
      - db

networks:
  SenaSoft:
    driver: bridge